export const countries = [
    { name: 'Argentina', code: 'AR' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Brasil', code: 'BR' },
    { name: 'Chile', code: 'CL' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'República Dominicana', code: 'DO' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Honduras', code: 'HN' },
    { name: 'México', code: 'MX' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Panamá', code: 'PA' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Perú', code: 'PE' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'España', code: 'ES' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Estados Unidos', code: 'US'},
];

export const currencies = [
    { name: 'Peso Argentino', code: 'ARS', symbol: '$' },
    { name: 'Boliviano', code: 'BOB', symbol: 'Bs.' },
    { name: 'Real Brasileño', code: 'BRL', symbol: 'R$' },
    { name: 'Peso Chileno', code: 'CLP', symbol: '$' },
    { name: 'Peso Colombiano', code: 'COP', symbol: '$' },
    { name: 'Colón Costarricense', code: 'CRC', symbol: '₡' },
    { name: 'Peso Cubano', code: 'CUP', symbol: '$' },
    { name: 'Peso Dominicano', code: 'DOP', symbol: 'RD$' },
    { name: 'Dólar estadounidense', code: 'USD', symbol: '$' },
    { name: 'Quetzal Guatemalteco', code: 'GTQ', symbol: 'Q' },
    { name: 'Lempira Hondureño', code: 'HNL', symbol: 'L' },
    { name: 'Peso Mexicano', code: 'MXN', symbol: '$' },
    { name: 'Córdoba Nicaragüense', code: 'NIO', symbol: 'C$' },
    { name: 'Balboa Panameño', code: 'PAB', symbol: 'B/.' },
    { name: 'Guaraní Paraguayo', code: 'PYG', symbol: '₲' },
    { name: 'Sol Peruano', code: 'PEN', symbol: 'S/.' },
    { name: 'Euro', code: 'EUR', symbol: '€' },
    { name: 'Peso Uruguayo', code: 'UYU', symbol: '$U' },
    { name: 'Bolívar Venezolano', code: 'VES', symbol: 'Bs.' },
];
